#!/usr/bin/python
#coding:utf-8

from pptx import Presentation

prs = Presentation('xxx.pptx')

# Text stores strings in dictionary format,
# one for each text run in presentation

text = {}
for x in range(len(prs.slides)):
    text[x] = []
    for shape in prs.slides[x].shapes:
        if not shape.has_text_frame:
            continue
        for paragraph in shape.text_frame.paragraphs:
            for run in paragraph.runs:
                text[x].append(run.text)
